- name: Copy munin configurations.
  become: yes
  template:
    src: munin.conf.j2
    dest: "/etc/munin/munin.conf"

- name: copy apache.conf file
  become: yes
  copy: src=apache24.conf dest=/etc/munin/apache24.conf

- name: add to etc/hosts
  become: yes
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.0\.1'
    line: '127.0.0.1 monitoring.normand'
  
- name: Copy vhost configurations.
  become: yes
  template:
    src: monitoring.normand.j2
    dest: "/etc/apache2/sites-available/monitoring.normand.conf"

- name: a2ensite 
  become: yes
  command: "sudo a2ensite monitoring.normand"

- name: Restart ssh
  become: yes
  service: name=munin-node state=restarted

- name: Restart ssh
  become: yes
  service: name=apache2 state=restarted